from pathlib import Path

from docx import Document

from backend.generators.base import BaseGenerator


class DocxGenerator(BaseGenerator):
    def generate(self, prompt: str, template_path: Path | None = None) -> Path:
        data = self._llm_json(
            'Return JSON: {"title": "...", "sections": [{"heading": "...", "content": "...", "bullets": ["..."]}]}',
            prompt,
        )
        tpl = template_path or self._get_template("docx")
        doc = Document(str(tpl)) if tpl and tpl.exists() else Document()
        title = data.get("title", "Document")
        doc.add_heading(title, 0)
        doc.add_paragraph(f"Generated by Loki — {Path().cwd()}")
        for section in data.get("sections", []):
            if section.get("heading"):
                doc.add_heading(section["heading"], level=1)
            if section.get("content"):
                doc.add_paragraph(section["content"])
            for bullet in section.get("bullets", []):
                doc.add_paragraph(bullet, style="List Bullet")
        out = self._unique_output_path(title.replace(" ", "_"), "docx")
        doc.save(str(out))
        self._audit.log("file_generated", {"type": "docx", "path": str(out)}, category="DOCUMENT")
        return out
