from pathlib import Path
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, PageBreak

from backend.generators.base import BaseGenerator


class PdfGenerator(BaseGenerator):
    def generate(self, prompt: str, template_path: Path | None = None) -> Path:
        data = self._llm_json(
            'Return JSON: {"title": "...", "sections": [{"heading": "...", "content": "...", "bullets": ["..."]}]}',
            prompt,
        )
        title = data.get("title", "Document")
        out = self._unique_output_path(title.replace(" ", "_"), "pdf")
        doc = SimpleDocTemplate(str(out), pagesize=letter)
        styles = getSampleStyleSheet()
        heading_style = ParagraphStyle("Heading", parent=styles["Heading1"], textColor=colors.HexColor("#1B4F8A"))
        story = []
        story.append(Paragraph(title, styles["Title"]))
        story.append(Paragraph(f"Generated by Loki — {datetime.now().strftime('%Y-%m-%d')}", styles["Normal"]))
        story.append(Spacer(1, 0.3 * inch))
        for section in data.get("sections", []):
            if section.get("heading"):
                story.append(Paragraph(section["heading"], heading_style))
            if section.get("content"):
                story.append(Paragraph(section["content"], styles["Normal"]))
            for bullet in section.get("bullets", []):
                story.append(Paragraph(f"• {bullet}", styles["Normal"]))
            story.append(Spacer(1, 0.15 * inch))
        doc.build(story)
        self._audit.log("file_generated", {"type": "pdf", "path": str(out)}, category="DOCUMENT")
        return out
