from pathlib import Path

from pptx import Presentation
from pptx.util import Inches, Pt

from backend.generators.base import BaseGenerator


class PptxGenerator(BaseGenerator):
    def generate(self, prompt: str, template_path: Path | None = None) -> Path:
        data = self._llm_json(
            'Return JSON: {"title": "...", "slides": [{"title": "...", "bullets": ["..."], "notes": "..."}]}',
            prompt,
        )
        tpl = template_path or self._get_template("pptx")
        prs = Presentation(str(tpl)) if tpl and tpl.exists() else Presentation()
        title = data.get("title", "Presentation")
        slide = prs.slides.add_slide(prs.slide_layouts[0])
        slide.shapes.title.text = title
        if len(slide.placeholders) > 1:
            slide.placeholders[1].text = "Generated by Loki"
        for s in data.get("slides", []):
            layout = prs.slide_layouts[1]
            slide = prs.slides.add_slide(layout)
            slide.shapes.title.text = s.get("title", "")
            body = slide.placeholders[1].text_frame
            body.clear()
            for i, bullet in enumerate(s.get("bullets", [])):
                p = body.paragraphs[0] if i == 0 else body.add_paragraph()
                p.text = bullet
                p.level = 0
            if s.get("notes"):
                slide.notes_slide.notes_text_frame.text = s["notes"]
        out = self._unique_output_path(title.replace(" ", "_"), "pptx")
        prs.save(str(out))
        self._audit.log("file_generated", {"type": "pptx", "path": str(out)}, category="DOCUMENT")
        return out
